### ISSUE TITLE
la scritta ciao sparisce se la finestra è troppo piccola

### ISSUE THREAD

**Issue by ssebastianoo** [chickenlory/chickenlory.github.io#1]
![immagine](https://user-images.githubusercontent.com/48064277/156036620-a5f9ba89-cfe1-43d5-9dd7-fcb6b346c050.png)

**Comment by ssebastianoo** [comment]
non mi sembra che il developer si preoccupi a fixare questo bug importantissimo che danneggia la salute del software da lui provvisto alla community open source di github

**Comment by ssebastianoo** [comment]
sono passati due mesi dalla segnalazione del problema ed il developer non sembra preoccuparsene, credo proprio che passerò ad un software i cui programmatori tengono alla loro community 😡

**Comment by ssebastianoo** [comment]
(un software tipo non overwatch)

**Comment by ssebastianoo** [comment]
qualcuno per una partita ad overwatch 2?

**Comment by chickenmatty** [comment]
hai provato a usare la rotellina per andare in basso?

**Comment by ssebastianoo** [comment]
ah no non ci gioca nessuno

**Comment by ssebastianoo** [comment]
> hai provato a usare la rotellina per andare in basso?

si, un utente mi aveva già consigliato questo tipo di azione in [questo forum](https://theratchetandclankunion.forumfree.it/) ma non è per niente user friendly

**Comment by chickenlory** [comment]
Risolto, grazie mille per la segnalazione!

**Comment by ssebastianoo** [comment]
> Risolto, grazie mille per la segnalazione!

non é vero
